### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by palmerc** [dankogai/swift-pons#3]
I've noticed that Complex and now PONS both suffer from lack of 32-bit support.

```
/// .hashValue -- conforms to Hashable
    public var hashValue:Int {
        let bits = sizeof(Int) * 4
        let mask = bits == 16 ? 0xffff : 0xffffFFFF
```

0xffffFFFF will not compile in Release mode unless you remove 32-bit targets leaving only arm64.

**Comment by dankogai** [comment]
`POComplex#hashValue` as of PONS 0.5.0 is defined as:

````swift
    /// hash value of `self`
    public var hashValue:Int {
        let bits = sizeof(Int) * 4
        return ((re.hashValue >> bits) << bits) | (im.hashValue >> bits)
    }
````

Which should not suffer from `0xffffFFFF`.  And so far as I see Framework-iOS builds fine for arm64, arm7 and arm7s.

**Comment by palmerc** [comment]
Oh! I missed that change. I had been meaning to mention this for a while, but good that you fixed it.
